language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"

notifications:
  slack: "gab-project:B06sOTldqFNp7pTSGUHJtGJd"

deploy:
  provider: heroku
  api_key: "9a24b740-d45d-41b2-a3bd-01cc46af69a1"
  app : "gab-project"